export const Users = [
  {
    "id": 1,
    "profile_img": "https://blueskygraphics.co.uk/wp-content/uploads/2021/08/The-Best-Computer-Build-For-A-Graphic-Designer-2022.jpg",
    "work": "Design",
    "title": "UX review presentations",
    "name": "Olivia Rhye",
    "date": "12 Jan 2022",
    "profile": "https://img.freepik.com/premium-photo/3d-illustration-cartoon-character-avatar-profile_1183071-176.jpg",
    "desc": "How do you create compelling presentations that wow your colleagues and impress your managers?",
  },
  {
    "id": 2,
    "profile_img": "https://www.mooc.org/hs-fs/hubfs/learn-programming-career-jpg.jpeg?width=500&name=learn-programming-career-jpg.jpeg",
    "work": "Product",
    "title": "Migrating to Linear 101",
    "name": "Phoenix Baker",
    "date": "13 Jan 2022",
    "profile": "https://static.vecteezy.com/system/resources/previews/026/976/736/non_2x/3d-icon-avatar-woman-illustration-of-smiling-happy-girl-cartoon-close-up-portrait-people-of-standing-teenager-on-isolated-on-transparent-background-generative-ai-png.png",
    "desc": "Linear helps streamline software projects, sprints, tasks, and bug tracking. Here’s how to get started.",
  },
  {
    "id": 3,
    "profile_img": "https://hexaware.com/wp-content/uploads/2018/06/leveraging-software-product-engineering-for-digital-transformation-e1569838706624.jpg",
    "work": "Software Engineering",
    "title": "Building your API Stack",
    "name": "Lana Steiner",
    "date": "14 Jan 2022",
    "profile": "https://thumbs.dreamstime.com/b/d-icon-avatar-cartoon-character-teenager-stylish-man-people-close-up-portrait-isolated-transparent-png-background-generative-ai-274955075.jpg",
    "desc": "The rise of RESTful APIs has been met by a rise in tools for creating, testing, and managing them.",
  },
  {
    "id": 4,
    "profile_img": "https://news.fit.edu/wp-content/uploads/2017/11/engineering-management-degree.jpg",
    "work": "Management",
    "title": "Bill Walsh leadership lessons",
    "name": "Alec Whitten",
    "date": "15 Jan 2022",
    "profile": "https://t3.ftcdn.net/jpg/05/99/32/28/360_F_599322870_hufBazDahX69a57xhcprgfn4WSjAlXZj.jpg",
    "desc": "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
  },
  {
    "id": 5,
    "profile_img": "https://s3.amazonaws.com/utep-uploads/wp-content/uploads/engineering_ucr/2022/08/15054617/product-design-engineer.jpg",
    "work": "Product",
    "title": "PM mental models",
    "name": "Demi WIlkinson",
    "date": "16 Jan 2022",
    "profile": "https://img.freepik.com/premium-photo/3d-style-avatar-profile-picture-featuring-male-character-generative-ai_739548-13625.jpg",
    "desc": "Mental models are simple expressions of complex processes or relationships.",
  },
  {
    "id": 6,
    "profile_img": "https://www.asme.org/getmedia/c9e1c463-c7ef-4dcb-9995-7e0c4383e89a/drafting.jpg.aspx?width=460&height=302&ext=.jpg",
    "work": "Design",
    "title": "What is Wireframing?",
    "name": "Candice Wu",
    "date": "17 Jan 2022",
    "profile": "https://img.freepik.com/premium-photo/3d-style-avatar-profile-picture-featuring-male-character-generative-ai_739548-13628.jpg",
    "desc": "Introduction to Wireframing and its Principles. Learn from the best in the industry.",
  },
  {
    "id": 7,
    "profile_img": "https://www.simscale.com/wp-content/uploads/2016/05/Product-Designer.jpg",
    "work": "Design",
    "title": "How collaboration makes us better designers",
    "name": "Natali Craig",
    "date": "18 Jan 2022",
    "profile": "https://img.freepik.com/premium-photo/3d-style-avatar-profile-picture-featuring-male-character-generative-ai_739548-13626.jpg",
    "desc": "Collaboration can make our teams stronger, and our indivual designs better.",
  },
  {
    "id": 8,
    "profile_img": "https://www.cameronmfg.com/hubfs/Engineering%20Design%20Process.jpg",
    "work": "Product",
    "title": "Our top 10 Javascript frameworks to uses",
    "name": "Drew Cano",
    "date": "18 Jan 2022",
    "profile": "https://img.freepik.com/premium-photo/stylish-man-flat-vector-profile-picture-ai-generated_606187-309.jpg",
    "desc": "JavaScript frameworks make development easy with extensive features and functionalities.",
  },
  {
    "id": 9,
    "profile_img": "https://blogs.opentext.com/wp-content/uploads/2024/06/opentext-image-blog-DX-contact-center-image4-1200x675-1-1024x576.png",
    "work": "Customer Service",
    "title": "Podcast: Creating a better CX Community",
    "name": "Orlando Diggs",
    "date": "20 Jan 2022",
    "profile": "https://img.freepik.com/premium-photo/criminologist-digital-avatar-generative-ai_934475-9136.jpg",
    "desc": "Starting a community doesn’t need to be complicated, but how do you get started?",
  },
];
